"""Baseline schema: every table in bursa.db.models as of the move to Alembic.

Autogenerated against an empty SQLite file, then hand-reviewed:
JSON columns use the same JSON/JSONB variant as the models, server
defaults use func.now() (CURRENT_TIMESTAMP on SQLite, now() on Postgres)
exactly as create_all renders them, and index creation is plain
op.create_index rather than batch blocks.

A database built by the old ``bursa init-db`` (Base.metadata.create_all)
is identical to this revision; adopt it with ``bursa db stamp``.

Revision ID: 0001_baseline
Revises:
Create Date: 2026-10-07

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

JSON_TYPE = sa.JSON().with_variant(postgresql.JSONB(), "postgresql")

# revision identifiers, used by Alembic.
revision: str = "0001_baseline"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.create_table(
        "benchmark_cache",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("ticker", sa.String(length=16), nullable=False),
        sa.Column("field_name", sa.String(length=64), nullable=False),
        sa.Column("period_end", sa.Date(), nullable=False),
        sa.Column("value", sa.Numeric(precision=24, scale=4), nullable=False),
        sa.Column(
            "fetched_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("ticker", "field_name", "period_end", name="uq_yf_cache"),
    )
    op.create_table(
        "companies",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("stock_code", sa.String(length=8), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("short_name", sa.String(length=64), nullable=True),
        sa.Column("market", sa.String(length=8), nullable=False),
        sa.Column("sector", sa.String(length=128), nullable=True),
        sa.Column("fy_end_month", sa.Integer(), nullable=True),
        sa.Column("is_watchlist", sa.Boolean(), nullable=False),
        sa.Column("ir_homepage_url", sa.Text(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("stock_code"),
    )
    op.create_table(
        "concepts",
        sa.Column("concept_key", sa.String(length=64), nullable=False),
        sa.Column("statement", sa.String(length=8), nullable=False),
        sa.Column("label", sa.String(length=160), nullable=False),
        sa.Column("parent_key", sa.String(length=64), nullable=True),
        sa.Column("is_subtotal", sa.Boolean(), nullable=False),
        sa.Column("typical_sign", sa.String(length=16), nullable=False),
        sa.Column("is_instant", sa.Boolean(), nullable=False),
        sa.Column("is_per_share", sa.Boolean(), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.ForeignKeyConstraint(["parent_key"], ["concepts.concept_key"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("concept_key"),
    )
    op.create_table(
        "job_progress",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("total", sa.Integer(), nullable=False),
        sa.Column("done", sa.Integer(), nullable=False),
        sa.Column("current", sa.String(length=256), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column(
            "started_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "benchmark_results",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("company_id", sa.Integer(), nullable=False),
        sa.Column("concept_key", sa.String(length=64), nullable=False),
        sa.Column("fiscal_year", sa.Integer(), nullable=False),
        sa.Column("source", sa.String(length=16), nullable=False),
        sa.Column("our_value", sa.Numeric(precision=24, scale=4), nullable=True),
        sa.Column("external_value", sa.Numeric(precision=24, scale=4), nullable=True),
        sa.Column("deviation_pct", sa.Float(), nullable=True),
        sa.Column("classification", sa.String(length=16), nullable=False),
        sa.Column("detail", sa.Text(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.ForeignKeyConstraint(["company_id"], ["companies.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "company_id", "concept_key", "fiscal_year", "source", name="uq_benchmark"
        ),
    )
    op.create_index("ix_benchmark_company", "benchmark_results", ["company_id"], unique=False)

    op.create_table(
        "concept_synonyms",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("concept_key", sa.String(length=64), nullable=False),
        sa.Column("statement", sa.String(length=8), nullable=False),
        sa.Column("pattern", sa.String(length=300), nullable=False),
        sa.Column("normalized", sa.String(length=300), nullable=False),
        sa.Column("lang", sa.String(length=8), nullable=False),
        sa.Column("origin", sa.String(length=16), nullable=False),
        sa.Column("company_id", sa.Integer(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.ForeignKeyConstraint(["company_id"], ["companies.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["concept_key"], ["concepts.concept_key"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "normalized", "statement", "company_id", name="uq_synonym_norm_stmt_company"
        ),
    )
    op.create_index(
        "ix_synonym_lookup", "concept_synonyms", ["normalized", "statement"], unique=False
    )

    op.create_table(
        "documents",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("company_id", sa.Integer(), nullable=True),
        sa.Column("doc_type", sa.String(length=24), nullable=False),
        sa.Column("source", sa.String(length=16), nullable=False),
        sa.Column("source_url", sa.Text(), nullable=True),
        sa.Column("original_filename", sa.String(length=512), nullable=False),
        sa.Column("file_sha256", sa.String(length=64), nullable=False),
        sa.Column("file_size", sa.Integer(), nullable=False),
        sa.Column("storage_path", sa.Text(), nullable=False),
        sa.Column("filed_date", sa.Date(), nullable=True),
        sa.Column("period_end_hint", sa.Date(), nullable=True),
        sa.Column("page_count", sa.Integer(), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("document_group_key", sa.String(length=128), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.ForeignKeyConstraint(["company_id"], ["companies.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("file_sha256"),
    )
    op.create_index(
        "ix_documents_company_filed", "documents", ["company_id", "filed_date"], unique=False
    )

    op.create_table(
        "periods",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("company_id", sa.Integer(), nullable=False),
        sa.Column("period_start", sa.Date(), nullable=True),
        sa.Column("period_end", sa.Date(), nullable=False),
        sa.Column("period_type", sa.String(length=8), nullable=False),
        sa.Column("fiscal_year", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["company_id"], ["companies.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "company_id", "period_start", "period_end", "period_type", name="uq_period"
        ),
    )
    op.create_index("ix_periods_company_end", "periods", ["company_id", "period_end"], unique=False)

    op.create_table(
        "document_pages",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("document_id", sa.Integer(), nullable=False),
        sa.Column("page_no", sa.Integer(), nullable=False),
        sa.Column("has_text_layer", sa.Boolean(), nullable=False),
        sa.Column("statement_guess", sa.String(length=8), nullable=True),
        sa.Column("guess_confidence", sa.Float(), nullable=True),
        sa.Column("heading_text", sa.Text(), nullable=True),
        sa.Column("width", sa.Float(), nullable=True),
        sa.Column("height", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(["document_id"], ["documents.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("document_id", "page_no", name="uq_page_per_doc"),
    )
    op.create_table(
        "extraction_runs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("document_id", sa.Integer(), nullable=False),
        sa.Column("layout_engine", sa.String(length=16), nullable=True),
        sa.Column("engine_versions", JSON_TYPE, nullable=True),
        sa.Column("prompt_version", sa.String(length=32), nullable=True),
        sa.Column("model", sa.String(length=64), nullable=True),
        sa.Column("llm_calls", sa.Integer(), nullable=False),
        sa.Column("synonym_hits", sa.Integer(), nullable=False),
        sa.Column("input_tokens", sa.Integer(), nullable=False),
        sa.Column("output_tokens", sa.Integer(), nullable=False),
        sa.Column("cost_cents", sa.Numeric(precision=12, scale=4), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.ForeignKeyConstraint(["document_id"], ["documents.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "scrape_attempts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("company_id", sa.Integer(), nullable=False),
        sa.Column("source", sa.String(length=16), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("document_id", sa.Integer(), nullable=True),
        sa.Column("detail", sa.Text(), nullable=True),
        sa.Column("run_label", sa.String(length=64), nullable=True),
        sa.Column(
            "checked_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.ForeignKeyConstraint(["company_id"], ["companies.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["document_id"], ["documents.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_scrape_attempts_run", "scrape_attempts", ["run_label", "status"], unique=False
    )

    op.create_table(
        "raw_rows",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("run_id", sa.Integer(), nullable=False),
        sa.Column("page_no", sa.Integer(), nullable=False),
        sa.Column("table_index", sa.Integer(), nullable=False),
        sa.Column("row_index", sa.Integer(), nullable=False),
        sa.Column("label_text", sa.Text(), nullable=False),
        sa.Column("cells", JSON_TYPE, nullable=False),
        sa.Column("bbox", JSON_TYPE, nullable=True),
        sa.Column("indent_level", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["run_id"], ["extraction_runs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("run_id", "page_no", "table_index", "row_index", name="uq_raw_row"),
    )
    op.create_index("ix_raw_rows_run_page", "raw_rows", ["run_id", "page_no"], unique=False)

    op.create_table(
        "statement_tables",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("run_id", sa.Integer(), nullable=False),
        sa.Column("page_no", sa.Integer(), nullable=False),
        sa.Column("table_index", sa.Integer(), nullable=False),
        sa.Column("statement", sa.String(length=8), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("scale_multiplier", sa.Integer(), nullable=False),
        sa.Column("scale_token", sa.String(length=64), nullable=True),
        sa.Column("column_map", JSON_TYPE, nullable=False),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(["run_id"], ["extraction_runs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("run_id", "page_no", "table_index", name="uq_statement_table"),
    )
    op.create_table(
        "validation_results",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("run_id", sa.Integer(), nullable=False),
        sa.Column("rule_key", sa.String(length=48), nullable=False),
        sa.Column("period_id", sa.Integer(), nullable=True),
        sa.Column("passed", sa.Boolean(), nullable=False),
        sa.Column("expected", sa.Numeric(precision=24, scale=4), nullable=True),
        sa.Column("actual", sa.Numeric(precision=24, scale=4), nullable=True),
        sa.Column("delta", sa.Numeric(precision=24, scale=4), nullable=True),
        sa.Column("detail", sa.Text(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.ForeignKeyConstraint(["period_id"], ["periods.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["run_id"], ["extraction_runs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_validation_run", "validation_results", ["run_id", "passed"], unique=False)

    op.create_table(
        "facts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("company_id", sa.Integer(), nullable=False),
        sa.Column("concept_key", sa.String(length=64), nullable=False),
        sa.Column("period_id", sa.Integer(), nullable=False),
        sa.Column("value", sa.Numeric(precision=24, scale=4), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("value_as_printed", sa.String(length=64), nullable=True),
        sa.Column("scale_multiplier", sa.Integer(), nullable=False),
        sa.Column("basis", sa.String(length=16), nullable=False),
        sa.Column("continuity", sa.String(length=16), nullable=False),
        sa.Column("reported_in_document_id", sa.Integer(), nullable=False),
        sa.Column("source_raw_row_id", sa.Integer(), nullable=True),
        sa.Column("source_col_index", sa.Integer(), nullable=True),
        sa.Column("run_id", sa.Integer(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("review_status", sa.String(length=16), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.ForeignKeyConstraint(["company_id"], ["companies.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["concept_key"], ["concepts.concept_key"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["period_id"], ["periods.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["reported_in_document_id"], ["documents.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["run_id"], ["extraction_runs.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["source_raw_row_id"], ["raw_rows.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "company_id",
            "concept_key",
            "period_id",
            "basis",
            "continuity",
            "reported_in_document_id",
            name="uq_fact_identity",
        ),
    )
    op.create_index(
        "ix_facts_lookup", "facts", ["company_id", "concept_key", "period_id"], unique=False
    )
    op.create_index("ix_facts_run", "facts", ["run_id"], unique=False)

    op.create_table(
        "review_items",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("run_id", sa.Integer(), nullable=False),
        sa.Column("document_id", sa.Integer(), nullable=False),
        sa.Column("raw_row_id", sa.Integer(), nullable=True),
        sa.Column("fact_id", sa.Integer(), nullable=True),
        sa.Column("reason", sa.String(length=64), nullable=False),
        sa.Column("detail", sa.Text(), nullable=True),
        sa.Column("severity", sa.Integer(), nullable=False),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("resolved_by", sa.String(length=128), nullable=True),
        sa.Column("resolution", JSON_TYPE, nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.ForeignKeyConstraint(["document_id"], ["documents.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["fact_id"], ["facts.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["raw_row_id"], ["raw_rows.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["run_id"], ["extraction_runs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_review_open", "review_items", ["resolved_at"], unique=False)


def downgrade() -> None:
    op.drop_index("ix_review_open", table_name="review_items")

    op.drop_table("review_items")
    op.drop_index("ix_facts_run", table_name="facts")
    op.drop_index("ix_facts_lookup", table_name="facts")

    op.drop_table("facts")
    op.drop_index("ix_validation_run", table_name="validation_results")

    op.drop_table("validation_results")
    op.drop_table("statement_tables")
    op.drop_index("ix_raw_rows_run_page", table_name="raw_rows")

    op.drop_table("raw_rows")
    op.drop_index("ix_scrape_attempts_run", table_name="scrape_attempts")

    op.drop_table("scrape_attempts")
    op.drop_table("extraction_runs")
    op.drop_table("document_pages")
    op.drop_index("ix_periods_company_end", table_name="periods")

    op.drop_table("periods")
    op.drop_index("ix_documents_company_filed", table_name="documents")

    op.drop_table("documents")
    op.drop_index("ix_synonym_lookup", table_name="concept_synonyms")

    op.drop_table("concept_synonyms")
    op.drop_index("ix_benchmark_company", table_name="benchmark_results")

    op.drop_table("benchmark_results")
    op.drop_table("job_progress")
    op.drop_table("concepts")
    op.drop_table("companies")
    op.drop_table("benchmark_cache")
